DROP TABLE IF EXISTS trust_ratings CASCADE;
DROP TABLE IF EXISTS opportunity_chains CASCADE;
DROP TABLE IF EXISTS opportunity_matches CASCADE;
DROP TABLE IF EXISTS opportunities CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS user_skills_assets CASCADE;
DROP TABLE IF EXISTS users CASCADE;
